In [1]:
import numpy as np
import os

In [5]:
file_path = "0301_1_hil.csv"
val_data_out = np.loadtxt(file_path,delimiter=',',max_rows=1024,skiprows=1,usecols=(0,1),dtype=np.float32)
val_data_in = np.loadtxt(file_path,delimiter=',',max_rows=1024,skiprows=1,usecols=(2,3,4,5),dtype=np.float32)

print(f"validate output data: \n{val_data_out}")
print(f"validate input data: \n{val_data_in}")

np.savetxt('val_input.csv',val_data_in,delimiter=',',fmt='%.8f')
np.savetxt('val_output.csv',val_data_out,delimiter=',',fmt='%.8f')


validate output data: 
[[ 184.  184.]
 [ 184.  286.]
 [ 286.  286.]
 ...
 [3254.  286.]
 [3357.  286.]
 [3357.  184.]]
validate input data: 
[[4685. 4367. 5095. 4632.]
 [4622. 4417. 5093. 4610.]
 [4639. 4447. 5109. 4606.]
 ...
 [5207. 4704. 4601. 4225.]
 [5238. 4695. 4661. 4199.]
 [5229. 4694. 4664. 4196.]]
